#  https://docs.docker.com/compose/compose-file/compose-file-v3/#build

version: "3.9"         # tells which version of compose file to use 
# creates a volume      :       docker volume create wordpress-volume 
volumes:
  wordpress-volume: {}
  database-volume: {}
  cache-volume: {}

# create containers
services:              # what containers to run 

  database:
    image: mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: redhat
    volumes:
    - database-volume:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == worker
      resources:
        reservations:                    # how much resource it can request
          cpus: '0.5'
          memory: 20M
        limits:                          # how much it can use overall 
          cpus: '1.0'
          memory: 500M

  cache:
    depends_on:
    - database
    image: redis
    ports:
    - 6379:6379
    volumes:
    - cache-volume:/tmp
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == worker
      resources:
        reservations:                    # how much resource it can request
          cpus: '0.5'
          memory: 20M
        limits:                          # how much it can use overall 
          cpus: '1.0'
          memory: 500M

  wordpress:           # name of the container
    depends_on:
    - cache
    - database
    image: wordpress   # image of the container 
    ports:
    - 80:80
    volumes:
    - wordpress-volume:/var/www/html
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: redhat
    deploy:
      replicas: 3
      placement:
        constraints:
        - node.role == worker
      resources:
        reservations:                    # how much resource it can request
          cpus: '0.5'
          memory: 20M
        limits:                          # how much it can use overall 
          cpus: '1.0'
          memory: 500M




  visualizer:
    image: dockersamples/visualizer
    deploy:
      mode: global
      placement:
        constraints: 
          - node.role == manager
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - "8080:8080"




# To run 
# docker-compose  -f  compose.yaml  up  -d  
